# Generated by Django 4.2.30 on 2026-09-15 12:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la tarea')),
                ('urgency', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'La urgencia mínima es 1'), django.core.validators.MaxValueValidator(4, 'La urgencia máxima es 4')], verbose_name='Urgencia (1-4)')),
                ('importance', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'La importancia mínima es 1'), django.core.validators.MaxValueValidator(4, 'La importancia máxima es 4')], verbose_name='Importancia (1-4)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción / Notas')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('quadrant', models.CharField(choices=[('Q1', 'Q1: Urgente e Importante'), ('Q2', 'Q2: No Urgente pero Importante'), ('Q3', 'Q3: Urgente pero No Importante'), ('Q4', 'Q4: No Urgente y No Importante'), ('DONE', 'Completada')], default='Q1', max_length=10, verbose_name='Cuadrante')),
                ('is_completed', models.BooleanField(default=False, verbose_name='¿Completada?')),
                ('email_notification_sent', models.BooleanField(default=False, verbose_name='Notificación enviada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='boards.board', verbose_name='Tablero')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-created_at'],
            },
        ),
    ]
