# Generated by Django 4.2.30 on 2026-09-13 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'La importancia mínima es 1'), django.core.validators.MaxValueValidator(4, 'La importancia máxima es 4')], verbose_name='Importancia (1-4)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='urgency',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'La urgencia mínima es 1'), django.core.validators.MaxValueValidator(4, 'La urgencia máxima es 4')], verbose_name='Urgencia (1-4)'),
        ),
    ]
