# Generated by Django 4.2.30 on 2026-09-13 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
        ('tasks', '0002_alter_task_importance_alter_task_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='boards.board', verbose_name='Tablero'),
        ),
    ]
