# Generated by Django 4.2.30 on 2026-09-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_enabled',
            field=models.BooleanField(default=False, verbose_name='Activar recordatorio'),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_offset',
            field=models.CharField(choices=[('at_time', 'A la hora del vencimiento'), ('5_min', '5 minutos antes'), ('15_min', '15 minutos antes'), ('1_hour', '1 hora antes'), ('2_hours', '2 horas antes'), ('1_day', '1 día antes'), ('2_days', '2 días antes'), ('1_week', '1 semana antes'), ('2_weeks', '2 semanas antes')], default='1_day', max_length=20, verbose_name='Antelación del recordatorio'),
        ),
    ]
