# Generated by Django 4.2.30 on 2026-09-11 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(blank=True, choices=[('#3B82F6', 'Azul'), ('#10B981', 'Verde'), ('#EF4444', 'Rojo'), ('#F59E0B', 'Naranja'), ('#8B5CF6', 'Púrpura'), ('#6B7280', 'Gris')], max_length=7, null=True, verbose_name='Color')),
                ('is_default', models.BooleanField(default=False, verbose_name='¿Tablero general?')),
                ('due_date', models.TimeField(blank=True, null=True, verbose_name='Fecha límite del tablero')),
                ('email_notifications_sent', models.BooleanField(default=False, verbose_name='Notificación enviada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Tablero',
                'verbose_name_plural': 'Tableros',
                'ordering': ['-created_at'],
            },
        ),
    ]
