# Generated by Django 4.2.30 on 2026-10-05 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['created_at'], 'verbose_name': 'Tablero', 'verbose_name_plural': 'Tableros'},
        ),
    ]
